### ISSUE TITLE
MIDI memory allocation error message could be improved

### ISSUE THREAD

**Issue by antennatree** [still-scene/t3#158]
![Screenshot 2022-09-28 040159](https://user-images.githubusercontent.com/51747615/192726692-03eb69b2-b20a-4a63-abfb-6a32682dd4be.png)

**Comment by ScreenDream** [comment]
Yeah, that is an old Error message from Windows actually, probably there since Windows 3.1 or something like that. Windows itself has it like "Not enough memory to open controller xyz"... Which is just wrong, since it should be saying "This midi device is already used by another application and I - Windows - am too darn stupid to have mmulti-user-midi-drivers as default"... ;-)

**Comment by pixtur** [comment]
Done
