### ISSUE TITLE
In Parameter window, default values should not have ↪️ marker

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#174]
Minor issue in parameter window

1) change a parameter
-> ↪️ is shown, which nicely allows to go back to default value with one click
2) edit parameter, so that the value is default 
-> ↪️ is still shown, click on it is somewhat useless because it has no effect (besides of removing the marker)

If fixed, ↪️ would also serve the purpose to indicate that a value is non-default

**Comment by pixtur** [comment]
This is by design: The default value is NOT just a value. It means "use the value that is defined by the Symbol for that parameter". This means, that you can, e.g. change the default Blend mode for all [Layer2d] instances. 
And sometimes is even makes sense to say "yes, I explicitly set this parameter 0.0, although it's the default, but I want o make sure that it will not be affected by changes to the default value".

Although advanced this feature is incredibly valuable for refining Operators and their behaviour.
