### ISSUE TITLE
frequency spectrum not getting updated when audio file content is changed

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#19]
- Add a soundtrack by selecting a file -> spectrum is generated
- Close t3  (not sure if necessary, but that's how I did it)
- Change the audio file, but keep the name
- Restart t3
- Reload the audio file 

-> Spectrum still shows the old frequencies
but audio plays correctly the new version

Win 11 laptop, version was https://github.com/still-scene/t3/commit/7f8e3334fb04415b4d976a1b5a5c896261f85d2a

**Comment by pixtur** [comment]
This is expected. There are several possibility to address this...

1. Just delete the png file manually and press the Reload button
2. We could remove and regenerate the sound image when pressing Reload.
3. We could add a checksum of date or filesize of the mp3 as prefix to the image filename (sounds hacky)
4. We could store the checksum in user or project settings (sounds convoluted).
5. We could create a checksum file next to the mp3 and png.
6. We could check, wether the png-file is older than the mp3 file (will not catch all required update and lead to even more confusion).

I personally think that for now deleting the soundimage and pressing Update is a sufficient work around.

Otherwise I would go for option 3.
