### ISSUE TITLE
Support for HiDPI screen and Windows Scaling

### ISSUE THREAD

**Issue by kikohs** [still-scene/t3#228]
I would love to use Tooll3 coming from cables.gl but the UI is very blurry on my screen (42'' 4k, 150%), so I can't.

This is probably related to this: https://github.com/ocornut/imgui/issues/1065
Fortunately there is a fix that needs to be integrated from this repo: https://github.com/thedmd/imgui/tree/feature/hidpi-support

Thank you very much.

**Comment by pixtur** [comment]
Thanks for putting some pressure on me to work on that. Although I couldn't really apply the solution mentioned by you, it put me into the right direction. Getting the correct UI scale resolution in .net core seems to be a bit finicky though. 

I believe I got it working on my system and experimented with auto can custom (150% and 200%) scale modes. Both look okay. I also went to the most obvious UI glitches caused by the UI scale factor. But there are probably many other areas that need improvement. (one being to switch to @2x and @1.5x icon scales).

I pushed the solution to the dev branch. I would be great, if you could report any all issues here.

Also this needs testing with Win11.
